<h1>Registrierung</h1>

<form method ="post" action="<?php echo $this->url();?>">
	<table>
		<tr>
			<th align="left"> Nutzername </th>
			<td> <input type="text" name="nutzer" /> </td>
		</tr>
		<tr>
			<th align="left"> Anrede </th>
			<td> <select name="anrede">
				<option value="0"> Herr </option>
				<option value="1"> Frau </option>
			</select> </td>
		</tr>
		<tr>
			<th align="left"> Vorname </th>
			<td> <input type="text" name="vorname" /> </td>
		</tr>
		<tr>
			<th align="left"> Nachname </th>
			<td> <input type="text" name="nachname" /> </td>
		</tr>
		<tr>
			<th align="left"> Passwort </th>
			<td> <input type="password" name="pass" /> </td>
		</tr>
		<tr>
			<th align="left"> Passwort(wiederholen) </th>
			<td> <input type="password" name="kontrolle" /> </td>
		</tr>
		<tr>
			<th align="left"> Email </th>
			<td> <input type="text" name="email" /> </td>
		</tr>
		<tr>
			<th> &nbsp; </th>
			<td> <input type="submit" name="create" value="registrieren" /> </td>
		</tr>
	</table>
</form>