<form method="post" action="<?php echo $this->url(array('controller' => 'index','action' => 'login'));?>">
	<table>
		<tr>
			<th align="left"> Nutzer </th>
			<td> <input type="text" name="nutzer" /> </td>
		</tr>
		<tr>
			<th align="left"> Passwort </th>
			<td> <input type="password" name="pass" /> </td>
		</tr>
		<tr>
			<th> &nbsp; </th>
			<td> <input type="submit" name="login" value="Anmelden" /> </td>
		</tr>
		<tr>
			<th colspan="2"> <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'register'));?>">registrieren</a> </th>
		</tr>
	</table>
</form>